# Generated by Django 6.0.8 on 2026-09-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventvaluedictionary',
            new_name='ml_event_va_event_c_8825ec_idx',
            old_name='idx_event_dict_cat_active',
        ),
        migrations.RenameIndex(
            model_name='faultepisode',
            new_name='ml_fault_ep_episode_e70d77_brin',
            old_name='idx_fault_episodes_start_brin',
        ),
        migrations.RenameIndex(
            model_name='faultepisode',
            new_name='ml_fault_ep_channel_d51405_idx',
            old_name='idx_fault_episodes_channel_start',
        ),
        migrations.RenameIndex(
            model_name='faultepisode',
            new_name='ml_fault_ep_episode_614135_idx',
            old_name='idx_fault_episodes_time_range',
        ),
        migrations.RenameIndex(
            model_name='forecastsnapshot',
            new_name='ml_forecast_forecas_cc93bb_idx',
            old_name='idx_forecast_type_updated',
        ),
        migrations.RenameIndex(
            model_name='mlprediction',
            new_name='ml_predicti_predict_566aa5_brin',
            old_name='idx_ml_predictions_time_brin',
        ),
        migrations.RenameIndex(
            model_name='mlprediction',
            new_name='ml_predicti_model_n_a7d4b7_idx',
            old_name='idx_ml_predictions_model_time',
        ),
        migrations.RenameIndex(
            model_name='mlprediction',
            new_name='ml_predicti_entity__b63ae8_idx',
            old_name='idx_ml_predictions_entity_model',
        ),
        migrations.RenameIndex(
            model_name='mlprediction',
            new_name='ml_predicti_model_n_b981dc_idx',
            old_name='idx_ml_predictions_model_label_time',
        ),
        migrations.AlterField(
            model_name='channelkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='alarm_count',
            field=models.BigIntegerField(default=0, verbose_name='Число тревог'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='channel_count',
            field=models.IntegerField(default=0, verbose_name='Число каналов'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='event_category',
            field=models.CharField(choices=[('fault', 'fault'), ('warning', 'warning'), ('detection', 'detection'), ('normal', 'normal'), ('unknown', 'unknown')], max_length=20, verbose_name='Категория события'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='event_count',
            field=models.BigIntegerField(default=0, verbose_name='Число событий'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='label_source',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Источник разметки'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='rule_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID правила'),
        ),
        migrations.AlterField(
            model_name='eventvaluedictionary',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Версия справочника'),
        ),
        migrations.AlterField(
            model_name='faultepisode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forecastsnapshot',
            name='forecast_type',
            field=models.CharField(max_length=50, verbose_name='Тип прогноза'),
        ),
        migrations.AlterField(
            model_name='forecastsnapshot',
            name='horizons',
            field=models.JSONField(default=dict, verbose_name='Горизонты'),
        ),
        migrations.AlterField(
            model_name='forecastsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forecastsnapshot',
            name='period',
            field=models.CharField(max_length=10, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='forecastsnapshot',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='engine',
            field=models.CharField(max_length=20, verbose_name='Движок'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='feature_count',
            field=models.IntegerField(default=0, verbose_name='Число признаков'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='Путь к файлу модели'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='granularity',
            field=models.CharField(max_length=50, verbose_name='Гранулярность'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='horizon_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Горизонт (дни)'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='horizon_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Горизонт (часы)'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метрики'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код модели'),
        ),
        migrations.AlterField(
            model_name='mlprediction',
            name='entity_id',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ID сущности'),
        ),
        migrations.AlterField(
            model_name='mlprediction',
            name='features_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='Снимок признаков'),
        ),
        migrations.AlterField(
            model_name='mlprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mlprediction',
            name='label',
            field=models.SmallIntegerField(default=0, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='mlprediction',
            name='model_name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='mlprediction',
            name='prediction_time',
            field=models.DateTimeField(db_index=True, verbose_name='Время прогноза'),
        ),
        migrations.AlterField(
            model_name='mlprediction',
            name='probability',
            field=models.FloatField(verbose_name='Вероятность'),
        ),
    ]
