# Generated by Django 6.0.8 on 2026-09-26 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchObject',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID объекта (ид_объект)')),
                ('hierarchy_level', models.PositiveSmallIntegerField(verbose_name='Уровень иерархии')),
                ('kind', models.CharField(choices=[('controlHouse', 'Диспетчерский пункт / шкаф управления'), ('guardObject', 'Охраняемый объект')], max_length=32, verbose_name='Вид объекта')),
                ('dispatcher_name', models.CharField(max_length=255, verbose_name='Диспетчерское название объекта')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dashboards.dispatchobject', verbose_name='Родительский объект')),
            ],
            options={
                'verbose_name': 'Объект диспетчеризации',
                'verbose_name_plural': 'Справочник объектов диспетчеризации',
            },
        ),
        migrations.CreateModel(
            name='SensorChannel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID канала данных (ид_канала_данных)')),
                ('engineering_system_type', models.CharField(max_length=255, verbose_name='Тип инженерной системы')),
                ('sensor_type', models.CharField(max_length=255, verbose_name='Тип датчика')),
                ('engineering_system_tag', models.CharField(max_length=255, verbose_name='Тег инженерной системы')),
                ('sensor_name', models.CharField(max_length=255, verbose_name='Название датчика')),
                ('dispatch_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_channels', to='dashboards.dispatchobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Канал датчика',
                'verbose_name_plural': 'Справочник каналов датчиков',
            },
        ),
        migrations.CreateModel(
            name='SensorEvent',
            fields=[
                ('pk', models.CompositePrimaryKey('source_event_id', 'occurred_at', blank=True, editable=False, primary_key=True, serialize=False)),
                ('source_event_id', models.BigIntegerField(verbose_name='ID события в источнике (ид_события)')),
                ('occurred_at', models.DateTimeField(help_text='Объединённые поля дата+время из журнала', verbose_name='Дата и время события')),
                ('is_alarm', models.BooleanField(default=False, verbose_name='Тревожное')),
                ('raw_value', models.CharField(help_text='Числовое показание либо текстовое название состояния', max_length=255, verbose_name='Значение датчика (сырое)')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboards.sensorchannel', verbose_name='Канал датчика')),
            ],
            options={
                'verbose_name': 'Событие датчика',
                'verbose_name_plural': 'Журнал событий датчиков',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=255, verbose_name='Тип датчика')),
                ('state_set_id', models.PositiveIntegerField(verbose_name='ID набора состояний')),
                ('name', models.CharField(max_length=255, verbose_name='Название состояния')),
                ('is_alarm', models.BooleanField(default=False, verbose_name='Тревожное состояние')),
            ],
            options={
                'verbose_name': 'Состояние датчика',
                'verbose_name_plural': 'Справочник состояний датчиков',
                'indexes': [models.Index(fields=['sensor_type', 'state_set_id'], name='dashboards__sensor__c44640_idx')],
                'constraints': [models.UniqueConstraint(fields=('sensor_type', 'state_set_id', 'name'), name='uniq_sensor_state')],
            },
        ),
        migrations.AddIndex(
            model_name='dispatchobject',
            index=models.Index(fields=['parent'], name='dashboards__parent__45ae57_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchobject',
            index=models.Index(fields=['kind'], name='dashboards__kind_d46608_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorchannel',
            index=models.Index(fields=['sensor_type'], name='dashboards__sensor__7494f0_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorchannel',
            index=models.Index(fields=['dispatch_object'], name='dashboards__dispatc_79dfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorevent',
            index=models.Index(fields=['occurred_at'], name='dashboards__occurre_57e746_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorevent',
            index=models.Index(fields=['channel', 'occurred_at'], name='dashboards__channel_9e4dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorevent',
            index=models.Index(fields=['is_alarm'], name='dashboards__is_alar_ee5193_idx'),
        ),
    ]
