# Generated by Django 6.0.8 on 2026-09-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_create_hypertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название точки')),
                ('requested_latitude', models.FloatField(verbose_name='Запрошенная широта')),
                ('requested_longitude', models.FloatField(verbose_name='Запрошенная долгота')),
                ('grid_latitude', models.FloatField(blank=True, null=True, verbose_name='Широта ячейки сетки (по ответу API)')),
                ('grid_longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота ячейки сетки (по ответу API)')),
                ('elevation_m', models.FloatField(blank=True, null=True, verbose_name='Высота, м')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Точка запроса погоды',
                'verbose_name_plural': 'Точки запроса погоды',
            },
        ),
        migrations.CreateModel(
            name='WeatherHourly',
            fields=[
                ('pk', models.CompositePrimaryKey('location', 'observed_at', blank=True, editable=False, primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField(verbose_name='Дата и время (локальное)')),
                ('temperature_2m', models.FloatField(blank=True, null=True, verbose_name='Температура на 2м, °C')),
                ('relative_humidity_2m', models.FloatField(blank=True, null=True, verbose_name='Отн. влажность на 2м, %')),
                ('pressure_msl', models.FloatField(blank=True, null=True, verbose_name='Давление на уровне моря, hPa')),
                ('precipitation', models.FloatField(blank=True, null=True, verbose_name='Осадки за предшествующий час, мм')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_records', to='dashboards.weatherlocation', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Погодные данные (час)',
                'verbose_name_plural': 'Погодная витрина (почасовая)',
                'ordering': ['observed_at'],
                'indexes': [models.Index(fields=['observed_at'], name='dashboards__observe_75157f_idx'), models.Index(fields=['location', 'observed_at'], name='dashboards__locatio_fd795c_idx')],
            },
        ),
    ]
