# Generated by Django 6.0.8 on 2026-09-28 22:42

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_weather_hypertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picket_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('collector', models.CharField(blank=True, default='', max_length=100)),
                ('okrug', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_pickets',
                'ordering': ['picket_id'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_technicians',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_id', models.CharField(max_length=100, unique=True)),
                ('forecast_type', models.CharField(choices=[('fire', 'Пожарный риск'), ('flooding', 'Риск затопления'), ('preventive-repair', 'Необходимость предупредительного ремонта'), ('channel-fault', 'Риск отказа канала'), ('system-fault', 'Риск отказа системы')], max_length=50)),
                ('period', models.CharField(choices=[('short', 'Краткосрочный'), ('long', 'Долгосрочный')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('horizons', models.JSONField(default=dict)),
                ('confidence_threshold', models.FloatField(default=0.58)),
                ('version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_forecasts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['forecast_type', 'updated_at'], name='mobile_fore_forecas_b1c4e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_id', models.CharField(max_length=100, unique=True)),
                ('task_description', models.CharField(blank=True, default='', max_length=255)),
                ('arrived_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='dashboards.picket')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='dashboards.technician')),
            ],
            options={
                'db_table': 'mobile_arrivals',
                'ordering': ['-arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_description', models.CharField(blank=True, default='', max_length=255)),
                ('status_map', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True, default='')),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('closed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboards.picket')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboards.technician')),
            ],
            options={
                'db_table': 'mobile_tasks',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='dashboards.task')),
            ],
            options={
                'db_table': 'mobile_checklist_items',
                'ordering': ['task', 'item_id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('Тревога', 'Тревога'), ('Допуск', 'Допуск'), ('Прогноз', 'Прогноз'), ('Связь', 'Связь'), ('ТО', 'ТО'), ('Смена', 'Смена'), ('Решение', 'Решение')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Открыто', 'Открыто'), ('Закрыто', 'Закрыто'), ('Ложное', 'Ложное'), ('', 'Без статуса')], default='Открыто', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_arrival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dashboards.arrival')),
                ('picket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dashboards.picket')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dashboards.task')),
            ],
            options={
                'db_table': 'mobile_events',
                'ordering': ['-occurred_at'],
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['occurred_at'], name='mobile_even_occurre_36209c_brin'), models.Index(fields=['event_type', 'occurred_at'], name='mobile_even_event_t_0700fb_idx'), models.Index(fields=['status', 'occurred_at'], name='mobile_even_status_718fb3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['closed_at'], name='mobile_task_closed__251c3d_brin'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['technician', 'closed_at'], name='mobile_task_technic_cd098d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['picket', 'closed_at'], name='mobile_task_picket__5bc311_idx'),
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['arrived_at'], name='mobile_arri_arrived_6ae82f_brin'),
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(fields=['technician', 'arrived_at'], name='mobile_arri_technic_5fb15b_idx'),
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(fields=['picket', 'arrived_at'], name='mobile_arri_picket__aba97f_idx'),
        ),
    ]
